//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_Test.RemoteWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sms.jwsserver.server.ema.ctc.com/", ConfigurationName="RemoteWebService.ISmsOperator")]
    public interface ISmsOperator {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SMS_Test.RemoteWebService.moMessageRes getSms(string arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<SMS_Test.RemoteWebService.moMessageRes> getSmsAsync(string arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SMS_Test.RemoteWebService.reportMessageRes getReport(string arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<SMS_Test.RemoteWebService.reportMessageRes> getReportAsync(string arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SMS_Test.RemoteWebService.mtMessageRes sendSms(string arg0, string arg1, string arg2, SMS_Test.RemoteWebService.mtMessage arg3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<SMS_Test.RemoteWebService.mtMessageRes> sendSmsAsync(string arg0, string arg1, string arg2, SMS_Test.RemoteWebService.mtMessage arg3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SMS_Test.RemoteWebService.balanceRes getBalance(string arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<SMS_Test.RemoteWebService.balanceRes> getBalanceAsync(string arg0, string arg1);
        
        // CODEGEN: 参数“arg3”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlArrayAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SMS_Test.RemoteWebService.bathSendSmsResponse bathSendSms(SMS_Test.RemoteWebService.bathSendSms request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<SMS_Test.RemoteWebService.bathSendSmsResponse> bathSendSmsAsync(SMS_Test.RemoteWebService.bathSendSms request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.jwsserver.server.ema.ctc.com/")]
    public partial class moMessageRes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private moMessageResDetail[] resDetailField;
        
        private string revStatField;
        
        private string revStatDesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public moMessageResDetail[] resDetail {
            get {
                return this.resDetailField;
            }
            set {
                this.resDetailField = value;
                this.RaisePropertyChanged("resDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string revStat {
            get {
                return this.revStatField;
            }
            set {
                this.revStatField = value;
                this.RaisePropertyChanged("revStat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string revStatDes {
            get {
                return this.revStatDesField;
            }
            set {
                this.revStatDesField = value;
                this.RaisePropertyChanged("revStatDes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.jwsserver.server.ema.ctc.com/")]
    public partial class moMessageResDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentField;
        
        private string demoField;
        
        private string phoneNumberField;
        
        private System.DateTime revTimeField;
        
        private bool revTimeFieldSpecified;
        
        private string subCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string demo {
            get {
                return this.demoField;
            }
            set {
                this.demoField = value;
                this.RaisePropertyChanged("demo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("phoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime revTime {
            get {
                return this.revTimeField;
            }
            set {
                this.revTimeField = value;
                this.RaisePropertyChanged("revTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool revTimeSpecified {
            get {
                return this.revTimeFieldSpecified;
            }
            set {
                this.revTimeFieldSpecified = value;
                this.RaisePropertyChanged("revTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string subCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
                this.RaisePropertyChanged("subCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.jwsserver.server.ema.ctc.com/")]
    public partial class balanceRes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string demoField;
        
        private string revStatField;
        
        private string revStatDesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string demo {
            get {
                return this.demoField;
            }
            set {
                this.demoField = value;
                this.RaisePropertyChanged("demo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string revStat {
            get {
                return this.revStatField;
            }
            set {
                this.revStatField = value;
                this.RaisePropertyChanged("revStat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string revStatDes {
            get {
                return this.revStatDesField;
            }
            set {
                this.revStatDesField = value;
                this.RaisePropertyChanged("revStatDes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.jwsserver.server.ema.ctc.com/")]
    public partial class mtMessageResDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string phoneNumberField;
        
        private string statField;
        
        private string statDesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("phoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string stat {
            get {
                return this.statField;
            }
            set {
                this.statField = value;
                this.RaisePropertyChanged("stat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string statDes {
            get {
                return this.statDesField;
            }
            set {
                this.statDesField = value;
                this.RaisePropertyChanged("statDes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.jwsserver.server.ema.ctc.com/")]
    public partial class mtMessageRes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private mtMessageResDetail[] resDetailField;
        
        private string smsIdField;
        
        private string subStatField;
        
        private string subStatDesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public mtMessageResDetail[] resDetail {
            get {
                return this.resDetailField;
            }
            set {
                this.resDetailField = value;
                this.RaisePropertyChanged("resDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string smsId {
            get {
                return this.smsIdField;
            }
            set {
                this.smsIdField = value;
                this.RaisePropertyChanged("smsId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string subStat {
            get {
                return this.subStatField;
            }
            set {
                this.subStatField = value;
                this.RaisePropertyChanged("subStat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string subStatDes {
            get {
                return this.subStatDesField;
            }
            set {
                this.subStatDesField = value;
                this.RaisePropertyChanged("subStatDes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.jwsserver.server.ema.ctc.com/")]
    public partial class mtMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentField;
        
        private string demoField;
        
        private string[] phoneNumberField;
        
        private System.DateTime sendTimeField;
        
        private bool sendTimeFieldSpecified;
        
        private string smsIdField;
        
        private string subCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string demo {
            get {
                return this.demoField;
            }
            set {
                this.demoField = value;
                this.RaisePropertyChanged("demo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phoneNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string[] phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("phoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime sendTime {
            get {
                return this.sendTimeField;
            }
            set {
                this.sendTimeField = value;
                this.RaisePropertyChanged("sendTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sendTimeSpecified {
            get {
                return this.sendTimeFieldSpecified;
            }
            set {
                this.sendTimeFieldSpecified = value;
                this.RaisePropertyChanged("sendTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string smsId {
            get {
                return this.smsIdField;
            }
            set {
                this.smsIdField = value;
                this.RaisePropertyChanged("smsId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string subCode {
            get {
                return this.subCodeField;
            }
            set {
                this.subCodeField = value;
                this.RaisePropertyChanged("subCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.jwsserver.server.ema.ctc.com/")]
    public partial class reportMessageResDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string phoneNumberField;
        
        private string smsIdField;
        
        private string statField;
        
        private string statDesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("phoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string smsId {
            get {
                return this.smsIdField;
            }
            set {
                this.smsIdField = value;
                this.RaisePropertyChanged("smsId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string stat {
            get {
                return this.statField;
            }
            set {
                this.statField = value;
                this.RaisePropertyChanged("stat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string statDes {
            get {
                return this.statDesField;
            }
            set {
                this.statDesField = value;
                this.RaisePropertyChanged("statDes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sms.jwsserver.server.ema.ctc.com/")]
    public partial class reportMessageRes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private reportMessageResDetail[] resDetailField;
        
        private string subStatField;
        
        private string subStatDesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public reportMessageResDetail[] resDetail {
            get {
                return this.resDetailField;
            }
            set {
                this.resDetailField = value;
                this.RaisePropertyChanged("resDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string subStat {
            get {
                return this.subStatField;
            }
            set {
                this.subStatField = value;
                this.RaisePropertyChanged("subStat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string subStatDes {
            get {
                return this.subStatDesField;
            }
            set {
                this.subStatDesField = value;
                this.RaisePropertyChanged("subStatDes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="bathSendSms", WrapperNamespace="http://sms.jwsserver.server.ema.ctc.com/", IsWrapped=true)]
    public partial class bathSendSms {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SMS_Test.RemoteWebService.mtMessage[] arg3;
        
        public bathSendSms() {
        }
        
        public bathSendSms(string arg0, string arg1, string arg2, SMS_Test.RemoteWebService.mtMessage[] arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="bathSendSmsResponse", WrapperNamespace="http://sms.jwsserver.server.ema.ctc.com/", IsWrapped=true)]
    public partial class bathSendSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public SMS_Test.RemoteWebService.mtMessageRes @return;
        
        public bathSendSmsResponse() {
        }
        
        public bathSendSmsResponse(SMS_Test.RemoteWebService.mtMessageRes @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISmsOperatorChannel : SMS_Test.RemoteWebService.ISmsOperator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsOperatorClient : System.ServiceModel.ClientBase<SMS_Test.RemoteWebService.ISmsOperator>, SMS_Test.RemoteWebService.ISmsOperator {
        
        public SmsOperatorClient() {
        }
        
        public SmsOperatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsOperatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsOperatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsOperatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SMS_Test.RemoteWebService.moMessageRes getSms(string arg0, string arg1) {
            return base.Channel.getSms(arg0, arg1);
        }
        
        public System.Threading.Tasks.Task<SMS_Test.RemoteWebService.moMessageRes> getSmsAsync(string arg0, string arg1) {
            return base.Channel.getSmsAsync(arg0, arg1);
        }
        
        public SMS_Test.RemoteWebService.reportMessageRes getReport(string arg0, string arg1) {
            return base.Channel.getReport(arg0, arg1);
        }
        
        public System.Threading.Tasks.Task<SMS_Test.RemoteWebService.reportMessageRes> getReportAsync(string arg0, string arg1) {
            return base.Channel.getReportAsync(arg0, arg1);
        }
        
        public SMS_Test.RemoteWebService.mtMessageRes sendSms(string arg0, string arg1, string arg2, SMS_Test.RemoteWebService.mtMessage arg3) {
            return base.Channel.sendSms(arg0, arg1, arg2, arg3);
        }
        
        public System.Threading.Tasks.Task<SMS_Test.RemoteWebService.mtMessageRes> sendSmsAsync(string arg0, string arg1, string arg2, SMS_Test.RemoteWebService.mtMessage arg3) {
            return base.Channel.sendSmsAsync(arg0, arg1, arg2, arg3);
        }
        
        public SMS_Test.RemoteWebService.balanceRes getBalance(string arg0, string arg1) {
            return base.Channel.getBalance(arg0, arg1);
        }
        
        public System.Threading.Tasks.Task<SMS_Test.RemoteWebService.balanceRes> getBalanceAsync(string arg0, string arg1) {
            return base.Channel.getBalanceAsync(arg0, arg1);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SMS_Test.RemoteWebService.bathSendSmsResponse SMS_Test.RemoteWebService.ISmsOperator.bathSendSms(SMS_Test.RemoteWebService.bathSendSms request) {
            return base.Channel.bathSendSms(request);
        }
        
        public SMS_Test.RemoteWebService.mtMessageRes bathSendSms(string arg0, string arg1, string arg2, SMS_Test.RemoteWebService.mtMessage[] arg3) {
            SMS_Test.RemoteWebService.bathSendSms inValue = new SMS_Test.RemoteWebService.bathSendSms();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            SMS_Test.RemoteWebService.bathSendSmsResponse retVal = ((SMS_Test.RemoteWebService.ISmsOperator)(this)).bathSendSms(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SMS_Test.RemoteWebService.bathSendSmsResponse> SMS_Test.RemoteWebService.ISmsOperator.bathSendSmsAsync(SMS_Test.RemoteWebService.bathSendSms request) {
            return base.Channel.bathSendSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SMS_Test.RemoteWebService.bathSendSmsResponse> bathSendSmsAsync(string arg0, string arg1, string arg2, SMS_Test.RemoteWebService.mtMessage[] arg3) {
            SMS_Test.RemoteWebService.bathSendSms inValue = new SMS_Test.RemoteWebService.bathSendSms();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((SMS_Test.RemoteWebService.ISmsOperator)(this)).bathSendSmsAsync(inValue);
        }
    }
}
